version: '3.3' 
services:
  web: 
    image: nawinnc/plex:0700 
    networks: 
    - webproxy 
    logging:
      driver: json-file 
    volumes: 
      - ${PLEX_MEDIA_PATH}:/media/
    container_name: plexapp
    deploy: 
      replicas: 1 
      labels: 
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.spcn15plex-https.entrypoints=websecure 
        - traefik.http.routers.spcn15plex-https.rule=Host("spcn15plex.xops.ipv9.xyz")
        - traefik.http.routers.spcn15plex-https.tls.certresolver=default
        - traefik.http.services.spcn15plex.loadbalancer.server.port=32400 
      resources: 
        reservations: 
          cpus: '0.1'
          memory: 10M
        limits: 
          cpus: '0.4'
          memory: 150M
networks: 
  webproxy: 
    external: true